import * as path from 'path';
import { HttpRequest } from '../models/httpRequest';
import {
    PostmanAuth,
    PostmanBody,
    PostmanCollection,
    PostmanEnvironment,
    PostmanFormParam,
    PostmanHeader,
    PostmanItem,
    PostmanRequest,
    PostmanSchemaV21,
    PostmanUrl,
    PostmanUrlQueryParam,
    PostmanVariable
} from '../models/postmanCollection';
import { getContentType } from './misc';
import { MimeUtility } from './mimeUtility';

const rawLanguageToContentType: Record<string, string> = {
    json: 'application/json',
    xml: 'application/xml',
    html: 'text/html',
    javascript: 'application/javascript',
    text: 'text/plain'
};

export function isPostmanCollection(json: any): json is PostmanCollection {
    return !!json && typeof json === 'object' && typeof json.info === 'object' && Array.isArray(json.item);
}

export function isPostmanEnvironment(json: any): json is PostmanEnvironment {
    return !!json
        && typeof json === 'object'
        && typeof json.name === 'string'
        && Array.isArray(json.values)
        && !Array.isArray(json.item);
}

// ---------------------------------------------------------------------------
// .http -> Postman Collection
// ---------------------------------------------------------------------------

export function buildCollectionFromHttpRequests(
    name: string,
    requests: { name: string; request: HttpRequest }[],
    variables: PostmanVariable[] = []
): PostmanCollection {
    const referencesBySourceRequest = collectRequestVariableReferences(requests);

    const item: PostmanItem[] = requests.map(({ name: itemName, request }) => {
        const postmanItem: PostmanItem = {
            name: itemName,
            request: buildPostmanRequest(request)
        };

        const references = referencesBySourceRequest.get(itemName);
        if (references?.size) {
            postmanItem.event = [{
                listen: 'test',
                script: { type: 'text/javascript', exec: buildRequestVariableTestScript(references) }
            }];
        }

        return postmanItem;
    });

    return {
        info: { name, schema: PostmanSchemaV21 },
        item,
        ...(variables.length ? { variable: variables } : {})
    };
}

// REST Client lets one request reference a prior request's response, e.g.
// {{alerts_active.response.body.$.features[0].properties.id}}. Postman has no
// equivalent syntax, but Postman variable names may contain dots/brackets, so
// the same literal expression can be kept as a collection variable's key --
// populated by a generated post-response "test" script on the SOURCE request
// (here, alerts_active) -- and every other request that already references
// {{alerts_active.response...}} keeps working unmodified.
const requestVariableReferenceRegex = /\{\{(\w+\.response\.(?:body|headers)(?:\.[^}]*)?)\}\}/g;
const requestVariableExpressionRegex = /^(\w+)\.response\.(body|headers)(?:\.(.*))?$/;

function collectRequestVariableReferences(requests: { name: string; request: HttpRequest }[]): Map<string, Set<string>> {
    const referencesBySourceRequest = new Map<string, Set<string>>();

    for (const { request } of requests) {
        const haystacks = [
            request.url,
            ...Object.values(request.headers).map(value => value?.toString() ?? ''),
            request.rawBody ?? ''
        ];

        for (const text of haystacks) {
            requestVariableReferenceRegex.lastIndex = 0;
            let match: RegExpExecArray | null;
            while ((match = requestVariableReferenceRegex.exec(text)) !== null) {
                const expression = match[1];
                const sourceMatch = requestVariableExpressionRegex.exec(expression);
                if (!sourceMatch) {
                    continue;
                }

                const sourceRequestName = sourceMatch[1];
                let references = referencesBySourceRequest.get(sourceRequestName);
                if (!references) {
                    references = new Set();
                    referencesBySourceRequest.set(sourceRequestName, references);
                }
                references.add(expression);
            }
        }
    }

    return referencesBySourceRequest;
}

function buildRequestVariableTestScript(expressions: Set<string>): string[] {
    const lines: string[] = [
        '// Auto-generated by REST Client export: populates {{name.response...}} variables referenced by other requests.'
    ];

    for (const expression of expressions) {
        const match = requestVariableExpressionRegex.exec(expression);
        if (!match) {
            continue;
        }

        const [, , part, rest] = match;
        lines.push('try {');

        if (part === 'headers') {
            if (rest) {
                lines.push(`    pm.collectionVariables.set(${JSON.stringify(expression)}, pm.response.headers.get(${JSON.stringify(rest)}));`);
            }
        } else if (!rest || rest === '*') {
            lines.push(`    pm.collectionVariables.set(${JSON.stringify(expression)}, pm.response.text());`);
        } else {
            const lodashPath = jsonPathToLodashPath(rest);
            if (lodashPath === null) {
                lines.push(`    // TODO: "${rest}" uses JSONPath syntax that can't be auto-translated (wildcards, filters, "..", or the backtick "@name" escape). Extract it manually.`);
            } else {
                lines.push('    const __body = pm.response.json();');
                lines.push(`    const __value = _.get(__body, ${JSON.stringify(lodashPath)});`);
                lines.push(`    if (__value !== undefined) { pm.collectionVariables.set(${JSON.stringify(expression)}, typeof __value === 'string' ? __value : JSON.stringify(__value)); }`);
            }
        }

        lines.push(`} catch (e) { /* leave ${JSON.stringify(expression)} unset on failure */ }`);
    }

    return lines;
}

function jsonPathToLodashPath(rawPath: string): string | null {
    let jsonPath = rawPath;
    if (jsonPath.startsWith('asJson.')) {
        jsonPath = jsonPath.slice('asJson.'.length);
    } else if (jsonPath.startsWith('asXml.')) {
        return null;
    }

    if (jsonPath.startsWith('$.')) {
        jsonPath = jsonPath.slice(2);
    } else if (jsonPath === '$') {
        jsonPath = '';
    }

    if (!jsonPath || /`|\.\.|\*|\[\?\(|@\./.test(jsonPath)) {
        return null;
    }

    return jsonPath;
}

function buildPostmanRequest(request: HttpRequest): PostmanRequest {
    const header = buildPostmanHeaders(request.headers);
    const body = buildPostmanBody(request, header);

    return {
        method: request.method,
        header,
        url: buildPostmanUrl(request.url),
        ...(body ? { body } : {})
    };
}

function buildPostmanHeaders(headers: HttpRequest['headers']): PostmanHeader[] {
    const result: PostmanHeader[] = [];
    for (const key in headers) {
        const value = headers[key];
        if (value === undefined) {
            continue;
        }

        const values = Array.isArray(value) ? value : [value.toString()];
        for (const v of values) {
            result.push({ key, value: v });
        }
    }
    return result;
}

function buildPostmanUrl(rawUrl: string): PostmanUrl {
    // Parsed by hand rather than with the WHATWG URL class, since a templated
    // authority (e.g. {{baseUrl}}/path) isn't a valid absolute URI and would
    // throw. Postman's own editor needs the host/path/query breakdown -- not
    // just `raw` -- to reliably populate the address bar on import, including
    // for templated base URLs (where the whole "{{baseUrl}}" token becomes a
    // single host segment).
    const url: PostmanUrl = { raw: rawUrl };

    let remainder = rawUrl;

    const protocolMatch = /^([a-zA-Z][a-zA-Z0-9+.-]*):\/\//.exec(remainder);
    if (protocolMatch) {
        url.protocol = protocolMatch[1];
        remainder = remainder.slice(protocolMatch[0].length);
    }

    const queryIndex = remainder.indexOf('?');
    let queryString = '';
    if (queryIndex !== -1) {
        queryString = remainder.slice(queryIndex + 1);
        remainder = remainder.slice(0, queryIndex);
    }

    const slashIndex = remainder.indexOf('/');
    const hostPart = slashIndex === -1 ? remainder : remainder.slice(0, slashIndex);
    const pathPart = slashIndex === -1 ? '' : remainder.slice(slashIndex + 1);

    url.host = hostPart.includes('{{') ? [hostPart] : hostPart.split('.').filter(segment => segment.length > 0);

    if (pathPart) {
        url.path = pathPart.split('/').filter(segment => segment.length > 0);
    }

    if (queryString) {
        url.query = queryString.split('&').filter(pair => pair.length > 0).map(pair => {
            const [key, ...rest] = pair.split('=');
            return { key: decodeURIComponent(key), value: decodeURIComponent(rest.join('=')) };
        });
    }

    return url;
}

function buildPostmanBody(request: HttpRequest, headers: PostmanHeader[]): PostmanBody | undefined {
    const rawBody = request.rawBody;
    if (!rawBody) {
        return undefined;
    }

    const contentType = getContentType(request.headers);

    if (MimeUtility.isFormUrlEncoded(contentType)) {
        const urlencoded: PostmanUrlQueryParam[] = rawBody.split('&').filter(pair => pair.length > 0).map(pair => {
            const [key, ...rest] = pair.split('=');
            return { key: decodeURIComponent(key), value: decodeURIComponent(rest.join('=')) };
        });
        return { mode: 'urlencoded', urlencoded };
    }

    if (MimeUtility.isMultiPartFormData(contentType)) {
        // No robust multipart parser -- pass the literal body through as raw text.
        return { mode: 'raw', raw: rawBody };
    }

    let language = 'text';
    if (MimeUtility.isJSON(contentType)) {
        language = 'json';
    } else if (MimeUtility.isXml(contentType)) {
        language = 'xml';
    } else if (MimeUtility.isHtml(contentType)) {
        language = 'html';
    } else if (MimeUtility.isJavaScript(contentType)) {
        language = 'javascript';
    }

    return { mode: 'raw', raw: rawBody, options: { raw: { language } } };
}

// ---------------------------------------------------------------------------
// Postman Collection -> .http
// ---------------------------------------------------------------------------

export function collectionToHttpFileContent(collection: PostmanCollection): string {
    const sections: string[] = [];

    const variables = (collection.variable ?? []).filter(v => !v.disabled);
    if (variables.length) {
        sections.push(variables.map(v => `@${v.key} = ${v.value}`).join('\n'));
    }

    const leaves: { name: string; request: PostmanRequest }[] = [];
    collectLeafRequests(collection.item ?? [], [], leaves);

    for (const { name, request } of leaves) {
        sections.push(`### ${name}\n${buildHttpBlock(name, request)}`);
    }

    return sections.join('\n\n') + '\n';
}

function collectLeafRequests(
    items: PostmanItem[],
    folderPath: string[],
    out: { name: string; request: PostmanRequest }[]
): void {
    for (const item of items) {
        if (item.item?.length) {
            collectLeafRequests(item.item, [...folderPath, item.name], out);
        } else if (item.request) {
            out.push({ name: [...folderPath, item.name].join(' / '), request: item.request });
        }
    }
}

function buildHttpBlock(name: string, request: PostmanRequest): string {
    const lines: string[] = [`# @name ${name}`];

    const { headerLines: authHeaderLines, queryParams } = buildAuthArtifacts(request.auth);

    let url = typeof request.url === 'string' ? request.url : (request.url.raw || buildUrlFromParts(request.url));
    if (queryParams.length) {
        const separator = url.includes('?') ? '&' : '?';
        url += separator + queryParams.map(q => `${q.key}=${q.value}`).join('&');
    }

    lines.push(`${(request.method || 'GET').toUpperCase()} ${url}`);

    const seenHeaderNames = new Set<string>();
    const headerLines: string[] = [];
    for (const line of authHeaderLines) {
        if (!line.startsWith('#')) {
            seenHeaderNames.add(line.slice(0, line.indexOf(':')).trim().toLowerCase());
        }
        headerLines.push(line);
    }

    for (const h of request.header ?? []) {
        if (h.disabled || seenHeaderNames.has(h.key.toLowerCase())) {
            continue;
        }
        seenHeaderNames.add(h.key.toLowerCase());
        headerLines.push(`${h.key}: ${h.value}`);
    }

    const { body, extraHeaderLines } = buildHttpBody(request.body);
    for (const line of extraHeaderLines) {
        const headerName = line.slice(0, line.indexOf(':')).trim().toLowerCase();
        if (!seenHeaderNames.has(headerName)) {
            seenHeaderNames.add(headerName);
            headerLines.push(line);
        }
    }

    lines.push(...headerLines);

    if (body !== undefined) {
        lines.push('');
        lines.push(body);
    }

    return lines.join('\n');
}

function buildUrlFromParts(url: PostmanUrl): string {
    const protocol = url.protocol ? `${url.protocol}://` : '';
    const host = (url.host ?? []).join('.');
    const pathPart = (url.path ?? []).join('/');
    const query = (url.query ?? []).filter(q => !q.disabled).map(q => `${q.key}=${q.value}`).join('&');
    return `${protocol}${host}${pathPart ? '/' + pathPart : ''}${query ? '?' + query : ''}`;
}

function buildAuthArtifacts(auth: PostmanAuth | undefined): { headerLines: string[]; queryParams: PostmanUrlQueryParam[] } {
    const headerLines: string[] = [];
    const queryParams: PostmanUrlQueryParam[] = [];

    if (!auth || auth.type === 'noauth') {
        return { headerLines, queryParams };
    }

    switch (auth.type) {
        case 'bearer': {
            const token = auth.bearer?.find(p => p.key === 'token')?.value ?? auth.bearer?.[0]?.value ?? '';
            headerLines.push(`Authorization: Bearer ${token}`);
            break;
        }
        case 'basic': {
            const username = auth.basic?.find(p => p.key === 'username')?.value ?? '';
            const password = auth.basic?.find(p => p.key === 'password')?.value ?? '';
            if (username.includes('{{') || password.includes('{{')) {
                headerLines.push(`# TODO: set Basic auth manually (username=${username}, password=${password})`);
            } else {
                headerLines.push(`Authorization: Basic ${Buffer.from(`${username}:${password}`).toString('base64')}`);
            }
            break;
        }
        case 'apikey': {
            const key = auth.apikey?.find(p => p.key === 'key')?.value ?? '';
            const value = auth.apikey?.find(p => p.key === 'value')?.value ?? '';
            const location = auth.apikey?.find(p => p.key === 'in')?.value ?? 'header';
            if (location === 'query') {
                queryParams.push({ key, value });
            } else {
                headerLines.push(`${key}: ${value}`);
            }
            break;
        }
        default:
            headerLines.push(`# TODO: auth type '${auth.type}' is not supported for automatic conversion, configure manually`);
    }

    return { headerLines, queryParams };
}

function buildHttpBody(body?: PostmanBody): { body?: string; extraHeaderLines: string[] } {
    if (!body?.mode) {
        return { extraHeaderLines: [] };
    }

    switch (body.mode) {
        case 'raw': {
            const language = body.options?.raw?.language;
            const contentType = language ? rawLanguageToContentType[language] : undefined;
            return { body: body.raw ?? '', extraHeaderLines: contentType ? [`Content-Type: ${contentType}`] : [] };
        }
        case 'urlencoded': {
            const pairs = (body.urlencoded ?? []).filter(p => !p.disabled).map(p => `${p.key}=${p.value}`);
            return { body: pairs.join('&'), extraHeaderLines: ['Content-Type: application/x-www-form-urlencoded'] };
        }
        case 'graphql': {
            const payload = {
                query: body.graphql?.query ?? '',
                variables: body.graphql?.variables ? JSON.parse(body.graphql.variables) : {}
            };
            return { body: JSON.stringify(payload, null, 2), extraHeaderLines: ['X-Request-Type: GraphQL'] };
        }
        case 'formdata': {
            const { body: multipartBody, boundary } = buildMultipartBody(body.formdata ?? []);
            return { body: multipartBody, extraHeaderLines: [`Content-Type: multipart/form-data; boundary=${boundary}`] };
        }
        default:
            return { extraHeaderLines: [] };
    }
}

function buildMultipartBody(params: PostmanFormParam[]): { body: string; boundary: string } {
    const boundary = `----RestClientBoundary${Date.now()}`;
    const parts: string[] = [];

    for (const param of params) {
        if (param.disabled) {
            continue;
        }

        if (param.type === 'file') {
            const fileName = param.src ? path.basename(param.src) : 'file';
            parts.push(
                `--${boundary}\r\nContent-Disposition: form-data; name="${param.key}"; filename="${fileName}"\r\n\r\n` +
                `# TODO: replace with "< /local/path/to/file" -- the original Postman file path is not portable`
            );
        } else {
            parts.push(`--${boundary}\r\nContent-Disposition: form-data; name="${param.key}"\r\n\r\n${param.value ?? ''}`);
        }
    }

    parts.push(`--${boundary}--`);
    return { body: parts.join('\r\n'), boundary };
}

// ---------------------------------------------------------------------------
// Postman Environment
// ---------------------------------------------------------------------------

export function environmentToVariableMap(env: PostmanEnvironment): { [key: string]: string } {
    const map: { [key: string]: string } = {};
    for (const value of env.values) {
        if (value.enabled !== false) {
            map[value.key] = value.value;
        }
    }
    return map;
}

export function buildPostmanEnvironment(name: string, variables: { [key: string]: string }): PostmanEnvironment {
    return {
        name,
        values: Object.entries(variables).map(([key, value]) => ({ key, value, enabled: true, type: 'default' })),
        _postman_variable_scope: 'environment'
    };
}
